wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      4: 3.9.5
      5: 0.11.1
      8:
      - 1
      - 5
learning_rate:
  desc: null
  value: 0.01
