wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.8.3
      5: 0.11.1
      8:
      - 1
      - 5
architecture:
  desc: null
  value: Autoencoder
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: FashionMNIST
epochs:
  desc: null
  value: 10
latent_dim:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: MSE
noise_factor:
  desc: null
  value: 1
train_test_split:
  desc: null
  value: 0.2
weight_decay:
  desc: null
  value: 0.001
